<?php
session_start();
//require 'authenticate.php';
require_once 'config/security_config.php';
$_SESSION["name"] = "quip";
?>
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="materialize/css/materialize.min.css"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="css/style.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="materialize/js/materialize.min.js"></script>

    <div class="navbar-fixed">
      <nav class="blue darken-3">
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">
            <i class="microscope">
              <img src="svg/camic_vector.svg" id="svg1" width="100%" height="100%" viewBox="0 0 640 480" preserveAspectRatio="xMaxYMax"/>
            </i>
            caMicroscope

          </a>
          <ul class="right hide-on-med-and-down">
            <li><a href="#upload">Upload</a></li>
            <li><a href="#view">View</a></li>
            <li><a href="#understand">Understand</a></li>
            <li><a href="#distribute">Distribute</a></li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="row">
      <div class="col s12 l4">
        <div class="card" id="upload">
          <div class="card-image">
            <div class="darkimg">
              <img src="img/upload.jpg">
            </div>
            <span class="card-title">Upload</span>
            <a class="btn-floating halfway-fab waves-effect waves-light red" href="/imageformuploader.php"><i class="material-icons">file_upload</i></a>
          </div>
          <div class="card-content">
            <p><b>Image Uploader</b>: Upload images here for collaboration, annotation and analysis. </p>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="card" id="view">
          <div class="card-image">
            <div class="darkimg">
              <img src="img/view.jpg">
            </div>
            <span class="card-title">View</span>
            <a class="btn-floating halfway-fab waves-effect waves-light red" href="/FlexTables/index.php"><i class="material-icons">pageview</i></a>
          </div>
          <div class="card-content">
            <p><b>caMicroscope</b>: View and annotate whole slide tissue images and nuclear segmentations.</p>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="card" id="understand">
          <div class="card-image">
            <div class="darkimg">
              <img src="img/understand.jpg">
            </div>
            <span class="card-title">Understand</span>
            <a class="btn-floating halfway-fab waves-effect waves-light red" href="/featurescapeapps/featurescape/u24Preview.php"><i class="material-icons">open_in_browser</i></a>
          </div>
          <div class="card-content">
            <p><b>FeatureScape</b>: A visual analytics platform for exploring slide-level imaging features generated by analysis of whole slide tissue images to QuIP.</p>
          </div>
        </div>
      </div>
      <div class="col s12 l4">
        <div class="card" id="distribute">
          <div class="card-image">
            <div class="darkimg">
              <img src="img/dist.jpg">
            </div>
            <span class="card-title">Distribute</span>
            <a class="btn-floating halfway-fab waves-effect waves-light red" href="https://github.com/SBU-BMI/quip_distro"><i class="material-icons">code</i></a>
          </div>
          <div class="card-content">
            <p><b>QuIP distribution and installation</b>: Report issues on QuIP or Install/Distribute this software.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="page-footer blue darken-4">
      <p style="color:white;">U24 CA18092401A1, <b>Tools to Analyze Morphology and Spatially Mapped Molecular Data</b>; <i>Joel Saltz
        PI</i> Stony Brook/Emory/Oak Ridge/Yale<br>NCIP/Leidos 14X138, <b>caMicroscope &ndash; A Digital Pathology
        Integrative Query System</b>; <i>Ashish Sharma PI</i> Emory/WUSTL/Stony Brook<br />
      </p>
    </div>

  </body>
</html>
